
#net.minecraft.scalar.pickupwidely.mod_PickupWidelySMP
[configuration]
	#String: "KEY_P"
	Key = "KEY_P"
	#Boolean: true
	StartMode = true
	#Double: 2.0
	horizontal = 2.0
	#Double: 1.0
	vertical = 1.0
	#Boolean: false
	select = false
	#String: ""
	itemIds = ""
	#String: "mod_pickupwidel"
	channelName = "mod_pickupwidel"

